/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/robot-optimized.glb -o src/components/robot/RobotGLTF.jsx --types false --keepnames 
Author: Konstantin Morozov (https://sketchfab.com/redstar0001)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/robot-a439c6136df649909659c321831125d1
Title: Robot
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/robot-optimized.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="����������001_R001_0" geometry={nodes['����������001_R001_0'].geometry} material={materials['R.001']} position={[0.018, 0.432, 0.01]} rotation={[-Math.PI / 2, 0, 0]} scale={2.409} />
      <mesh name="����������001_B001_0" geometry={nodes['����������001_B001_0'].geometry} material={materials['B.001']} position={[0.195, 0.491, 0.01]} rotation={[-Math.PI / 2, 0, 0]} scale={2.245} />
      <mesh name="����������001_G001_0" geometry={nodes['����������001_G001_0'].geometry} material={materials['G.001']} position={[0.015, 0.439, 0.01]} rotation={[-Math.PI / 2, 0, 0]} scale={2.416} />
    </group>
  )
}

useGLTF.preload('/robot-optimized.glb')
